<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Localization</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SpiceLogic.HtmlEditor.WPF" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SpiceLogic.HtmlEditor.Localization\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="underline.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
