<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>FullEditorDemoVB</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SpiceLogic.HtmlEditor.WPF" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="curly_underline_for_spell_checker.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
